### PR TITLE
Pi Detection 

### LINKED ISSUE #53: Pi Detection
Raspberry Pi 1B not detected:

`$ cat /proc/cpuinfo`

```
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 000d
Serial          : 00000000c5b4676c
```

### PR DESCRIPTION
**Pull request by cdimascio**
fixes #53

### CODE REVIEW

**Comment by victordibia** [comment]
@usefulthink .. some help needed with reviewing the above.
-V.

**Comment by usefulthink** [comment]
I'm sorry, I didn't see that notification at first. Merging right away! Thank you so much!

**Comment by victordibia** [comment]
Awesome .. thanks!

**Comment by usefulthink** [comment]
I'll try to get a new version to npm when I get home later.

**Comment by usefulthink** [comment]
just released v0.8.2 to npm with your fix in it. Thanks again!

**Comment by divya2100** [comment]
Thanks @usefulthink @victordibia for all the help !!!

**Pull request merged**
